### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by visenco** [ecomteck/module-advanced-contact#4]
After installing your Advanced Contact and Core module I am getting this error: Notice: Undefined index: id in /home/u5964p41342/domains/bakmina.com/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

**Comment by ecomteck** [comment]
Dear Visenco,
Please let me know what magento 2 version of your site? We tested the module on magento 2.3.0, 2.3.1 it is working properly.

**Comment by ecomteck** [comment]
> After installing your Advanced Contact and Core module I am getting this error: Notice: Undefined index: id in /home/u5964p41342/domains/bakmina.com/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

Please download the module core at here: https://github.com/ecomteck/module-core/archive/1.3.10.zip
Then setup upgrade for your site.

**Comment by visenco** [comment]
2.3.2Op 3 sep. 2019 12:20 schreef Ecomteck <notifications@github.com>:Dear Visenco,
Please let me know what magento 2 version of your site? We tested the module on magento 2.3.0, 2.3.1 it is working properly.

**Comment by ecomteck** [comment]
Dear,
Have a nice day!
We are testing the module on magento 2.3.2 on local site to update the module files if we get the issue as that.

**Comment by ecomteck** [comment]
The issues was resolved by update Module Ecomteck Core https://github.com/ecomteck/module-core/archive/1.3.10.zip
